os: linux
language: android
licenses:
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'
android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - android-27
jdk: oraclejdk8
sudo: false
addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - libstdc++6
      - fonts-droid

cache:
  directories:
    - $HOME/.pub-cache

install:
  - git clone https://github.com/flutter/flutter.git -b stable --depth 1
  - export PATH=./flutter/bin:$PATH
  - flutter doctor
  - flutter --version

script:
  - mkdir -p ~/.gradle && echo "org.gradle.daemon=false" >> ~/.gradle/gradle.properties
  - flutter packages get
  - flutter analyze --no-pub --no-current-package lib/ test/
  - flutter test --no-pub test/


before_deploy:
  # Set up git user name and tag this commit
  - flutter build apk --debug
  - git config --local user.name "MatyiFKBT"
  - git config --local user.email "mmatyi1999@gmail.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key:
    secure: BPJaQxvxBfcQ2k7fmf8YoNUvDGqgFLmER6JeRPRXt0PrkoL3MOtuH81cvBpwYWcAv+I4wfVeWu+m3sPCCAxdOD0isYVODG3DlM3PARwMrd1FwTjsc68GV8DZUEi5XJD4gTrJPSJBwWCw9fLh5DSItMN4QCZ4wB5A98SeEkOwxISkOtJjELUPDO6fd2qGswCgnjnt4ns9c3rgeVRpUUIU06wJyX37lmw7hb8etNQdzco8TlaCtWtsnZOs5dJ88g+MRLupvjkkqgvvaL1JJ0K6WXl8PKzlfpWexDOHDp9hSWmSAj6qjZWC5UGUIlzNe54gIrhM8m8tdH5PO4/TmFlkC4fkDM8Pz3PP4zVmlkDgVcn6iUJAWoQiqtVqAOcScfBQH7it6sheGYMeqVEwsB44TPLe4MtYvH7SiS0ZayYwym+6ZCW5uFQ5qJhklMrJeyxKbabxo8ny+AJ4ZwiP3Xw2PIUXbVXd5U1VGoinpvZaa+QBHc0rAFh6+/4XpYODn23amAwFMuekMQl1/DvV0NIcCAMPkg0Z0WMzZDgu7A7IA34su/oDGWPxpfqluUR9D7hLjpF8W2Mef5x3syMmvoC5YbqnUDsPtglLAOUKxqO1E7q3cHUCeEZamzRbiHY83sZueYsoAYaqj6WJBBjkC56Acsqrj9v5Un1Nn15BPNCcVkQ=
  file: build/app/outputs/apk/app.apk
  skip_cleanup: true
  on:
    repo: MatyiFKBT/portfolio_app
