language: dart
dist: bionic
addons:
  apt:
    packages:
      - lib32stdc++6
install:
  - git clone https://github.com/flutter/flutter.git -b stable --depth 1
  - export PATH=./flutter/bin:$PATH
  - flutter doctor
  - flutter --version
script:
  - flutter packages get
  - flutter analyze --no-pub --no-current-package lib/ test/
  - flutter test --no-pu
  - flutter build apk --debug
cache:
  directories:
    - "$HOME/.pub-cache"
deploy:
  provider: releases
  api_key:
    secure: BPJaQxvxBfcQ2k7fmf8YoNUvDGqgFLmER6JeRPRXt0PrkoL3MOtuH81cvBpwYWcAv+I4wfVeWu+m3sPCCAxdOD0isYVODG3DlM3PARwMrd1FwTjsc68GV8DZUEi5XJD4gTrJPSJBwWCw9fLh5DSItMN4QCZ4wB5A98SeEkOwxISkOtJjELUPDO6fd2qGswCgnjnt4ns9c3rgeVRpUUIU06wJyX37lmw7hb8etNQdzco8TlaCtWtsnZOs5dJ88g+MRLupvjkkqgvvaL1JJ0K6WXl8PKzlfpWexDOHDp9hSWmSAj6qjZWC5UGUIlzNe54gIrhM8m8tdH5PO4/TmFlkC4fkDM8Pz3PP4zVmlkDgVcn6iUJAWoQiqtVqAOcScfBQH7it6sheGYMeqVEwsB44TPLe4MtYvH7SiS0ZayYwym+6ZCW5uFQ5qJhklMrJeyxKbabxo8ny+AJ4ZwiP3Xw2PIUXbVXd5U1VGoinpvZaa+QBHc0rAFh6+/4XpYODn23amAwFMuekMQl1/DvV0NIcCAMPkg0Z0WMzZDgu7A7IA34su/oDGWPxpfqluUR9D7hLjpF8W2Mef5x3syMmvoC5YbqnUDsPtglLAOUKxqO1E7q3cHUCeEZamzRbiHY83sZueYsoAYaqj6WJBBjkC56Acsqrj9v5Un1Nn15BPNCcVkQ=
  file: build\app\outputs\apk\debug\app-debug.apk
  skip_cleanup: true
  on:
    repo: MatyiFKBT/portfolio_app
