name: portfolio_app
description: Simple portfolio app using Flutter.

version: 1.0.0+1

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Marker
      fonts:
        - asset: fonts/Marker.ttf
    - family: Sans Pro
      fonts:
        - asset: fonts/ss.ttf
